# -*- mode: ruby -*-
# vi: set ft=ruby :

SCRIPT_PATH_COMMON = "../scripts/centos-common.sh"
SCRIPT_PATH_WEB = "../scripts/centos-web.sh"
SCRIPT_PATH_DB = "../scripts/centos-db.sh"

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  # Common block
  config.vm.box_check_update = false

  config.vm.provision "shell",
	path: SCRIPT_PATH_COMMON

  # Web block
  config.vm.define "web" do |web|

	web.vm.hostname = "web-server"

	web.vm.network "private_network", ip: "192.168.10.2"
  
    web.vm.network "forwarded_port", guest: 80, host: 5000

    web.vm.synced_folder "../common_files/", "/home/content/"

    web.vm.provision "shell",
	  path: SCRIPT_PATH_WEB
  end

  # Db clock
  config.vm.define "db" do |db|

	db.vm.hostname = "db-server"

	db.vm.network "private_network", ip: "192.168.10.3"

    db.vm.provision "shell",
      path: SCRIPT_PATH_DB

  end

end
